// ============================================================
// PublishOps — Comprehensive Mock Data
// ============================================================

export const dashboardStats = {
  activeTopics: { value: 34, trend: 12.5, label: 'Active Topics', icon: 'topics' },
  contentBuffer: { value: 72, trend: 8.3, label: 'Content Buffer (hrs)', icon: 'buffer' },
  todayPosts: { value: 11, trend: -2.1, label: "Today's Posts", icon: 'posts' },
  weeklyEngagement: { value: '24.8K', trend: 18.7, label: 'Weekly Engagement', icon: 'engagement' },
};

export const pipelineStages = [
  {
    id: 1,
    name: 'Discovery',
    shortName: 'Discover',
    status: 'completed',
    icon: 'search',
    processedCount: 156,
    errorCount: 0,
    avgTime: '2.3s',
    lastRun: '2026-06-16T11:45:00Z',
    description: 'Scrapes trending topics from Reddit, X, Google Trends',
  },
  {
    id: 2,
    name: 'Scoring',
    shortName: 'Score',
    status: 'completed',
    icon: 'chart',
    processedCount: 142,
    errorCount: 2,
    avgTime: '1.8s',
    lastRun: '2026-06-16T11:46:00Z',
    description: 'Calculates composite scores using weighted algorithm',
  },
  {
    id: 3,
    name: 'Scripting',
    shortName: 'Script',
    status: 'running',
    icon: 'edit',
    processedCount: 89,
    errorCount: 1,
    avgTime: '12.4s',
    lastRun: '2026-06-16T11:48:00Z',
    description: 'Generates platform-optimized scripts via GPT-4',
    currentItem: 'Why Rust is Replacing C++ in Embedded Systems',
  },
  {
    id: 4,
    name: 'Voiceover',
    shortName: 'Voice',
    status: 'idle',
    icon: 'mic',
    processedCount: 76,
    errorCount: 0,
    avgTime: '8.1s',
    lastRun: '2026-06-16T11:30:00Z',
    description: 'Synthesizes narration with ElevenLabs API',
  },
  {
    id: 5,
    name: 'Assembly',
    shortName: 'Assemble',
    status: 'idle',
    icon: 'film',
    processedCount: 72,
    errorCount: 3,
    avgTime: '45.2s',
    lastRun: '2026-06-16T11:20:00Z',
    description: 'Combines media assets with FFmpeg pipeline',
  },
  {
    id: 6,
    name: 'Review',
    shortName: 'Review',
    status: 'idle',
    icon: 'check',
    processedCount: 68,
    errorCount: 0,
    avgTime: '3.5s',
    lastRun: '2026-06-16T11:15:00Z',
    description: 'Quality checks and compliance validation',
  },
  {
    id: 7,
    name: 'Publishing',
    shortName: 'Publish',
    status: 'idle',
    icon: 'upload',
    processedCount: 64,
    errorCount: 1,
    avgTime: '6.7s',
    lastRun: '2026-06-16T11:10:00Z',
    description: 'Uploads to platforms via APIs at optimal times',
  },
];

export const topics = [
  {
    id: 't1',
    title: 'Why Rust is Replacing C++ in Embedded Systems',
    compositeScore: 92,
    velocity: 88,
    evergreen: 75,
    platformFit: 96,
    saturation: 15,
    source: 'Reddit',
    status: 'accepted',
    category: 'Programming',
    discoveredAt: '2026-06-16T08:30:00Z',
  },
  {
    id: 't2',
    title: 'The Hidden Cost of Microservices Nobody Talks About',
    compositeScore: 89,
    velocity: 82,
    evergreen: 91,
    platformFit: 88,
    saturation: 22,
    source: 'Hacker News',
    status: 'accepted',
    category: 'Architecture',
    discoveredAt: '2026-06-16T07:15:00Z',
  },
  {
    id: 't3',
    title: 'Apple Vision Pro 2: What Developers Need to Know',
    compositeScore: 87,
    velocity: 95,
    evergreen: 42,
    platformFit: 90,
    saturation: 58,
    source: 'Twitter/X',
    status: 'scripting',
    category: 'Hardware',
    discoveredAt: '2026-06-16T09:00:00Z',
  },
  {
    id: 't4',
    title: 'Building a RAG Pipeline with LangChain in 2026',
    compositeScore: 85,
    velocity: 78,
    evergreen: 83,
    platformFit: 92,
    saturation: 35,
    source: 'Reddit',
    status: 'accepted',
    category: 'AI/ML',
    discoveredAt: '2026-06-16T06:45:00Z',
  },
  {
    id: 't5',
    title: 'PostgreSQL vs MySQL: The 2026 Benchmark Results',
    compositeScore: 83,
    velocity: 71,
    evergreen: 88,
    platformFit: 85,
    saturation: 28,
    source: 'Google Trends',
    status: 'accepted',
    category: 'Databases',
    discoveredAt: '2026-06-16T05:30:00Z',
  },
  {
    id: 't6',
    title: 'How Stripe Handles 500M API Calls Per Day',
    compositeScore: 81,
    velocity: 65,
    evergreen: 92,
    platformFit: 87,
    saturation: 18,
    source: 'Hacker News',
    status: 'review',
    category: 'Infrastructure',
    discoveredAt: '2026-06-15T22:00:00Z',
  },
  {
    id: 't7',
    title: 'CSS Container Queries Changed How I Build Layouts',
    compositeScore: 79,
    velocity: 62,
    evergreen: 85,
    platformFit: 90,
    saturation: 30,
    source: 'Twitter/X',
    status: 'accepted',
    category: 'Frontend',
    discoveredAt: '2026-06-15T20:15:00Z',
  },
  {
    id: 't8',
    title: 'Kubernetes Autoscaling: KEDA vs HPA Deep Dive',
    compositeScore: 77,
    velocity: 58,
    evergreen: 80,
    platformFit: 82,
    saturation: 25,
    source: 'Reddit',
    status: 'accepted',
    category: 'DevOps',
    discoveredAt: '2026-06-15T18:30:00Z',
  },
  {
    id: 't9',
    title: 'The WebAssembly Revolution is Finally Here',
    compositeScore: 76,
    velocity: 85,
    evergreen: 60,
    platformFit: 78,
    saturation: 42,
    source: 'Google Trends',
    status: 'rejected',
    category: 'Web',
    discoveredAt: '2026-06-15T16:00:00Z',
  },
  {
    id: 't10',
    title: 'Why Senior Devs Are Moving Back to Monoliths',
    compositeScore: 91,
    velocity: 90,
    evergreen: 70,
    platformFit: 95,
    saturation: 40,
    source: 'Twitter/X',
    status: 'accepted',
    category: 'Architecture',
    discoveredAt: '2026-06-15T14:45:00Z',
  },
  {
    id: 't11',
    title: 'Building Real-Time Apps with Supabase Edge Functions',
    compositeScore: 74,
    velocity: 68,
    evergreen: 72,
    platformFit: 80,
    saturation: 20,
    source: 'Reddit',
    status: 'accepted',
    category: 'Backend',
    discoveredAt: '2026-06-15T12:30:00Z',
  },
  {
    id: 't12',
    title: 'OpenAI Codex 3 vs GitHub Copilot X: Honest Review',
    compositeScore: 88,
    velocity: 92,
    evergreen: 38,
    platformFit: 94,
    saturation: 62,
    source: 'Twitter/X',
    status: 'scripting',
    category: 'AI/ML',
    discoveredAt: '2026-06-15T10:00:00Z',
  },
  {
    id: 't13',
    title: 'Zero-Downtime Deployments: A Practical Guide',
    compositeScore: 73,
    velocity: 55,
    evergreen: 95,
    platformFit: 78,
    saturation: 15,
    source: 'Hacker News',
    status: 'accepted',
    category: 'DevOps',
    discoveredAt: '2026-06-15T08:00:00Z',
  },
  {
    id: 't14',
    title: 'React Server Components: 1 Year Later',
    compositeScore: 82,
    velocity: 75,
    evergreen: 65,
    platformFit: 91,
    saturation: 48,
    source: 'Reddit',
    status: 'accepted',
    category: 'Frontend',
    discoveredAt: '2026-06-14T22:00:00Z',
  },
  {
    id: 't15',
    title: 'How I Cut My AWS Bill by 73% With Spot Instances',
    compositeScore: 86,
    velocity: 80,
    evergreen: 88,
    platformFit: 86,
    saturation: 12,
    source: 'Hacker News',
    status: 'accepted',
    category: 'Cloud',
    discoveredAt: '2026-06-14T19:30:00Z',
  },
  {
    id: 't16',
    title: 'GraphQL Federation: Lessons from Production',
    compositeScore: 71,
    velocity: 52,
    evergreen: 82,
    platformFit: 76,
    saturation: 20,
    source: 'Reddit',
    status: 'review',
    category: 'API',
    discoveredAt: '2026-06-14T15:00:00Z',
  },
];

export const contentItems = [
  {
    id: 'c1',
    title: 'Why Senior Devs Are Moving Back to Monoliths',
    platform: 'YouTube',
    format: 'Short-form Video',
    status: 'published',
    thumbnail: null,
    views: 45200,
    likes: 3100,
    comments: 287,
    shares: 542,
    engagementRate: 8.7,
    publishedAt: '2026-06-15T14:00:00Z',
    duration: '58s',
  },
  {
    id: 'c2',
    title: 'The Hidden Cost of Microservices',
    platform: 'TikTok',
    format: 'Short-form Video',
    status: 'published',
    thumbnail: null,
    views: 128400,
    likes: 12800,
    comments: 945,
    shares: 2340,
    engagementRate: 12.5,
    publishedAt: '2026-06-15T16:30:00Z',
    duration: '47s',
  },
  {
    id: 'c3',
    title: 'Rust vs C++ in Embedded: A Visual Guide',
    platform: 'Instagram',
    format: 'Carousel',
    status: 'published',
    thumbnail: null,
    views: 23100,
    likes: 2890,
    comments: 156,
    shares: 890,
    engagementRate: 17.0,
    publishedAt: '2026-06-15T10:00:00Z',
    duration: '10 slides',
  },
  {
    id: 'c4',
    title: 'PostgreSQL vs MySQL: Which Should You Choose?',
    platform: 'YouTube',
    format: 'Short-form Video',
    status: 'scheduled',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    scheduledFor: '2026-06-16T15:00:00Z',
    duration: '52s',
  },
  {
    id: 'c5',
    title: 'RAG Pipeline Architecture Breakdown',
    platform: 'LinkedIn',
    format: 'Thread',
    status: 'published',
    thumbnail: null,
    views: 8900,
    likes: 672,
    comments: 89,
    shares: 234,
    engagementRate: 11.2,
    publishedAt: '2026-06-14T09:00:00Z',
    duration: '5 posts',
  },
  {
    id: 'c6',
    title: 'How Stripe Handles Scale — Explained Simply',
    platform: 'TikTok',
    format: 'Short-form Video',
    status: 'review',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    duration: '55s',
  },
  {
    id: 'c7',
    title: 'Container Queries: The CSS Feature You\'re Missing',
    platform: 'Twitter/X',
    format: 'Thread',
    status: 'published',
    thumbnail: null,
    views: 34500,
    likes: 1890,
    comments: 234,
    shares: 678,
    engagementRate: 8.1,
    publishedAt: '2026-06-14T18:00:00Z',
    duration: '8 tweets',
  },
  {
    id: 'c8',
    title: 'KEDA vs HPA: Kubernetes Autoscaling Showdown',
    platform: 'YouTube',
    format: 'Short-form Video',
    status: 'assembling',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    duration: '60s',
  },
  {
    id: 'c9',
    title: 'I Cut My AWS Bill by 73%',
    platform: 'TikTok',
    format: 'Short-form Video',
    status: 'published',
    thumbnail: null,
    views: 89700,
    likes: 7650,
    comments: 543,
    shares: 1890,
    engagementRate: 11.2,
    publishedAt: '2026-06-13T12:00:00Z',
    duration: '44s',
  },
  {
    id: 'c10',
    title: 'React Server Components: Was It Worth It?',
    platform: 'Instagram',
    format: 'Carousel',
    status: 'scripting',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    duration: '8 slides',
  },
  {
    id: 'c11',
    title: 'Zero-Downtime Deployments in 60 Seconds',
    platform: 'YouTube',
    format: 'Short-form Video',
    status: 'scheduled',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    scheduledFor: '2026-06-17T10:00:00Z',
    duration: '59s',
  },
  {
    id: 'c12',
    title: 'GraphQL Federation: The Good, Bad & Ugly',
    platform: 'LinkedIn',
    format: 'Thread',
    status: 'published',
    thumbnail: null,
    views: 5600,
    likes: 423,
    comments: 67,
    shares: 145,
    engagementRate: 11.3,
    publishedAt: '2026-06-13T08:00:00Z',
    duration: '4 posts',
  },
  {
    id: 'c13',
    title: 'WebAssembly: Beyond the Browser',
    platform: 'Twitter/X',
    format: 'Thread',
    status: 'voiceover',
    thumbnail: null,
    views: 0,
    likes: 0,
    comments: 0,
    shares: 0,
    engagementRate: 0,
    publishedAt: null,
    duration: '6 tweets',
  },
];

export const scheduledPosts = [
  { id: 's1', title: 'PostgreSQL vs MySQL: Which Should You Choose?', platform: 'YouTube', scheduledFor: '2026-06-16T15:00:00Z', status: 'queued', format: 'Short-form Video' },
  { id: 's2', title: 'Why Rust Dominates Embedded Systems', platform: 'TikTok', scheduledFor: '2026-06-16T17:30:00Z', status: 'queued', format: 'Short-form Video' },
  { id: 's3', title: 'Microservices Cost Analysis Carousel', platform: 'Instagram', scheduledFor: '2026-06-16T19:00:00Z', status: 'queued', format: 'Carousel' },
  { id: 's4', title: 'Vision Pro 2 Developer Guide', platform: 'YouTube', scheduledFor: '2026-06-16T21:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's5', title: 'RAG Pipeline Tips Thread', platform: 'Twitter/X', scheduledFor: '2026-06-17T08:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's6', title: 'Zero-Downtime Deployments in 60 Seconds', platform: 'YouTube', scheduledFor: '2026-06-17T10:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's7', title: 'Kubernetes Scaling Deep Dive', platform: 'LinkedIn', scheduledFor: '2026-06-17T12:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's8', title: 'AWS Cost Optimization Hacks', platform: 'TikTok', scheduledFor: '2026-06-17T14:30:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's9', title: 'CSS Container Queries Tutorial', platform: 'Instagram', scheduledFor: '2026-06-17T16:00:00Z', status: 'pending', format: 'Carousel' },
  { id: 's10', title: 'Stripe Architecture Explained', platform: 'YouTube', scheduledFor: '2026-06-17T18:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's11', title: 'Monolith vs Microservices Debate', platform: 'Twitter/X', scheduledFor: '2026-06-18T09:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's12', title: 'Codex 3 vs Copilot X Showdown', platform: 'TikTok', scheduledFor: '2026-06-18T11:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's13', title: 'React Server Components Guide', platform: 'Instagram', scheduledFor: '2026-06-18T13:00:00Z', status: 'pending', format: 'Carousel' },
  { id: 's14', title: 'GraphQL Federation Lessons', platform: 'LinkedIn', scheduledFor: '2026-06-18T15:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's15', title: 'WebAssembly Use Cases 2026', platform: 'YouTube', scheduledFor: '2026-06-18T17:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's16', title: 'Supabase Edge Functions Tutorial', platform: 'TikTok', scheduledFor: '2026-06-19T10:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's17', title: 'Database Indexing Explained', platform: 'YouTube', scheduledFor: '2026-06-19T14:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's18', title: 'Docker Compose Best Practices', platform: 'Twitter/X', scheduledFor: '2026-06-19T16:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's19', title: 'System Design: URL Shortener', platform: 'Instagram', scheduledFor: '2026-06-20T11:00:00Z', status: 'pending', format: 'Carousel' },
  { id: 's20', title: 'CI/CD Pipeline Optimization Tips', platform: 'LinkedIn', scheduledFor: '2026-06-20T09:00:00Z', status: 'pending', format: 'Thread' },
  { id: 's21', title: 'Bun vs Node.js Performance Test', platform: 'TikTok', scheduledFor: '2026-06-20T15:00:00Z', status: 'pending', format: 'Short-form Video' },
  { id: 's22', title: 'Tailwind vs Vanilla CSS — The Truth', platform: 'YouTube', scheduledFor: '2026-06-20T18:00:00Z', status: 'pending', format: 'Short-form Video' },
];

export const analyticsData = {
  summary: {
    totalViews: { value: '1.2M', trend: 22.4 },
    avgCTR: { value: '6.8%', trend: 1.2 },
    totalSaves: { value: '45.2K', trend: 15.8 },
    engagementRate: { value: '9.4%', trend: 3.1 },
    followerGrowth: { value: '+8.2K', trend: 28.5 },
  },
  daily: Array.from({ length: 30 }, (_, i) => {
    const date = new Date('2026-05-18');
    date.setDate(date.getDate() + i);
    const base = 30000 + Math.random() * 20000;
    return {
      date: date.toISOString().split('T')[0],
      views: Math.round(base + Math.sin(i / 3) * 8000),
      engagement: Math.round((base * 0.08) + Math.random() * 800),
      saves: Math.round((base * 0.03) + Math.random() * 300),
    };
  }),
  byPlatform: [
    { platform: 'YouTube', views: 420000, engagement: 38500, color: '#FF0000' },
    { platform: 'TikTok', views: 380000, engagement: 52000, color: '#00f2ea' },
    { platform: 'Instagram', views: 195000, engagement: 28700, color: '#E1306C' },
    { platform: 'Twitter/X', views: 145000, engagement: 12400, color: '#1DA1F2' },
    { platform: 'LinkedIn', views: 60000, engagement: 8200, color: '#0A66C2' },
  ],
  byFormat: [
    { format: 'Short Video', count: 45, views: 680000, engagement: 72000 },
    { format: 'Carousel', count: 22, views: 285000, engagement: 38000 },
    { format: 'Thread', count: 31, views: 198000, engagement: 24500 },
    { format: 'Long Video', count: 8, views: 37000, engagement: 5300 },
  ],
  feedbackWeights: [
    { week: 'W1', velocity: 0.30, evergreen: 0.25, fit: 0.25, saturation: 0.20 },
    { week: 'W2', velocity: 0.28, evergreen: 0.27, fit: 0.26, saturation: 0.19 },
    { week: 'W3', velocity: 0.25, evergreen: 0.28, fit: 0.28, saturation: 0.19 },
    { week: 'W4', velocity: 0.27, evergreen: 0.26, fit: 0.29, saturation: 0.18 },
    { week: 'W5', velocity: 0.26, evergreen: 0.27, fit: 0.30, saturation: 0.17 },
    { week: 'W6', velocity: 0.24, evergreen: 0.28, fit: 0.31, saturation: 0.17 },
  ],
};

export const recentActivity = [
  { id: 'a1', type: 'published', message: 'Published "Why Senior Devs Are Moving Back to Monoliths" to YouTube', timestamp: '2026-06-16T11:45:00Z', stage: 'Publishing' },
  { id: 'a2', type: 'completed', message: 'Voiceover generated for "KEDA vs HPA Showdown"', timestamp: '2026-06-16T11:30:00Z', stage: 'Voiceover' },
  { id: 'a3', type: 'discovered', message: 'Discovered 12 new trending topics from Reddit', timestamp: '2026-06-16T11:15:00Z', stage: 'Discovery' },
  { id: 'a4', type: 'scored', message: 'Scored 142 topics — 34 above threshold', timestamp: '2026-06-16T11:00:00Z', stage: 'Scoring' },
  { id: 'a5', type: 'error', message: 'Assembly failed for "WebAssembly Beyond Browser" — FFmpeg timeout', timestamp: '2026-06-16T10:45:00Z', stage: 'Assembly' },
  { id: 'a6', type: 'published', message: 'Published "The Hidden Cost of Microservices" to TikTok', timestamp: '2026-06-16T10:30:00Z', stage: 'Publishing' },
  { id: 'a7', type: 'completed', message: 'Script approved for "PostgreSQL vs MySQL Benchmarks"', timestamp: '2026-06-16T10:15:00Z', stage: 'Review' },
  { id: 'a8', type: 'scripting', message: 'Generating script for "Rust in Embedded Systems"', timestamp: '2026-06-16T10:00:00Z', stage: 'Scripting' },
  { id: 'a9', type: 'published', message: 'Published "Rust vs C++ Visual Guide" carousel to Instagram', timestamp: '2026-06-16T09:45:00Z', stage: 'Publishing' },
  { id: 'a10', type: 'completed', message: 'Assembly completed for "AWS Cost Optimization"', timestamp: '2026-06-16T09:30:00Z', stage: 'Assembly' },
];

export const pipelineRuns = Array.from({ length: 20 }, (_, i) => ({
  id: `run-${100 - i}`,
  startedAt: new Date(Date.now() - (i * 3600000 + Math.random() * 1800000)).toISOString(),
  completedAt: i < 18 ? new Date(Date.now() - (i * 3600000 - 300000)).toISOString() : null,
  status: i === 0 ? 'running' : i === 5 ? 'failed' : 'completed',
  topicsProcessed: Math.floor(Math.random() * 20) + 5,
  contentGenerated: Math.floor(Math.random() * 8) + 1,
  errors: i === 5 ? 2 : Math.random() > 0.8 ? 1 : 0,
  duration: i < 18 ? `${Math.floor(Math.random() * 5) + 2}m ${Math.floor(Math.random() * 50) + 10}s` : 'In progress',
}));

export const platformRules = {
  youtube: {
    name: 'YouTube',
    color: '#FF0000',
    signals: [
      { signal: 'Watch Time', weight: 'Very High', description: 'Total minutes watched is the #1 ranking factor' },
      { signal: 'Click-Through Rate', weight: 'High', description: 'Thumbnail + title CTR from impressions' },
      { signal: 'Audience Retention', weight: 'Very High', description: 'Percentage of video watched, especially first 30s' },
      { signal: 'Engagement Velocity', weight: 'High', description: 'Speed of likes, comments, shares after publish' },
      { signal: 'Session Duration', weight: 'Medium', description: 'Does your video lead to more YouTube watching?' },
      { signal: 'Subscriber Conversion', weight: 'Medium', description: 'New subscriptions from your video' },
    ],
    formats: {
      shorts: { maxDuration: '60s', aspectRatio: '9:16', maxSize: '256MB' },
      longForm: { maxDuration: '12h', aspectRatio: '16:9', maxSize: '256GB' },
    },
    optimalHours: [9, 10, 11, 14, 15, 16, 17, 20, 21],
    tips: [
      'Hook viewers in the first 3 seconds with a bold claim or question',
      'Use pattern interrupts every 15-20 seconds to maintain retention',
      'End with a strong CTA — subscribe, comment, or watch next',
      'Shorts algorithm favors re-watchable content under 30 seconds',
    ],
  },
  tiktok: {
    name: 'TikTok',
    color: '#00f2ea',
    signals: [
      { signal: 'Completion Rate', weight: 'Very High', description: 'Full video watches and rewatches are king' },
      { signal: 'Shares', weight: 'Very High', description: 'Shares to DMs and other platforms boost reach 10x' },
      { signal: 'Comments', weight: 'High', description: 'Especially reply threads and controversial takes' },
      { signal: 'Follows from Video', weight: 'High', description: 'New followers gained from this specific video' },
      { signal: 'Audio Usage', weight: 'Medium', description: 'If others use your sound, massive amplification' },
      { signal: 'Saves', weight: 'High', description: 'Bookmarks indicate high-value educational content' },
    ],
    formats: {
      video: { maxDuration: '10m', aspectRatio: '9:16', maxSize: '287MB' },
      photo: { maxCount: '35 photos', aspectRatio: '9:16', maxSize: '20MB each' },
    },
    optimalHours: [7, 8, 12, 13, 17, 18, 19, 22, 23],
    tips: [
      'First frame must be visually arresting — no slow intros',
      'Use trending sounds but add original commentary',
      'Educational content with text overlays gets 3x saves',
      'Post 3-5 times per day for maximum algorithmic favor',
    ],
  },
  instagram: {
    name: 'Instagram',
    color: '#E1306C',
    signals: [
      { signal: 'Saves', weight: 'Very High', description: 'Saves are weighted higher than likes in 2026' },
      { signal: 'Shares to Stories', weight: 'Very High', description: 'Reshares amplify reach to new audiences' },
      { signal: 'Carousel Completion', weight: 'High', description: 'Swiping through all slides signals quality' },
      { signal: 'Comments Length', weight: 'High', description: 'Longer, meaningful comments boost ranking' },
      { signal: 'Profile Visits', weight: 'Medium', description: 'Post → profile visits indicate interest' },
      { signal: 'Reel Replays', weight: 'High', description: 'Rewatching reels is a strong positive signal' },
    ],
    formats: {
      reels: { maxDuration: '90s', aspectRatio: '9:16', maxSize: '250MB' },
      carousel: { maxSlides: '20', aspectRatio: '1:1 or 4:5', maxSize: '30MB per image' },
      story: { maxDuration: '60s', aspectRatio: '9:16', maxSize: '250MB' },
    },
    optimalHours: [8, 9, 11, 12, 17, 18, 19, 20],
    tips: [
      'Carousels get 3x more engagement than single images',
      'First slide must be a scroll-stopper — bold text + visual',
      'Use 3-5 relevant hashtags (less is more in 2026)',
      'Reels under 15 seconds get the most replays',
    ],
  },
  twitter: {
    name: 'Twitter/X',
    color: '#1DA1F2',
    signals: [
      { signal: 'Replies & Conversation', weight: 'Very High', description: 'Threads with active discussion get amplified' },
      { signal: 'Bookmarks', weight: 'High', description: 'Private saves signal high-value content' },
      { signal: 'Retweets & Quotes', weight: 'High', description: 'Distribution through network amplification' },
      { signal: 'Time Spent on Post', weight: 'Medium', description: 'Dwell time indicates quality content' },
      { signal: 'Link Clicks', weight: 'Medium', description: 'External link engagement (penalized in feed rank)' },
      { signal: 'Follower Quality', weight: 'Medium', description: 'Engagement from high-follower accounts matters more' },
    ],
    formats: {
      tweet: { maxLength: '280 chars', media: 'Up to 4 images or 1 video' },
      thread: { maxTweets: '25', bestLength: '5-10 tweets' },
      video: { maxDuration: '140s', maxSize: '512MB' },
    },
    optimalHours: [8, 9, 10, 12, 13, 17, 18],
    tips: [
      'First tweet of a thread is your headline — make it irresistible',
      'Use numbers and specifics: "5 lessons" beats "some lessons"',
      'Threads with 5-8 tweets perform best for tech content',
      'Avoid external links in the first tweet — add in reply instead',
    ],
  },
  linkedin: {
    name: 'LinkedIn',
    color: '#0A66C2',
    signals: [
      { signal: 'Dwell Time', weight: 'Very High', description: 'Time spent reading your post is the #1 signal' },
      { signal: 'Comments', weight: 'Very High', description: 'Especially within first hour of posting' },
      { signal: 'Reactions', weight: 'High', description: 'Insightful and Celebrate reactions weighted higher' },
      { signal: 'Reposts', weight: 'High', description: 'Shares to network with added commentary' },
      { signal: 'Profile Views', weight: 'Medium', description: 'Post leading to profile visits signals relevance' },
      { signal: 'External Clicks', weight: 'Low', description: 'LinkedIn deprioritizes posts with external links' },
    ],
    formats: {
      post: { maxLength: '3000 chars', bestLength: '1200-1500 chars' },
      article: { maxLength: 'Unlimited', bestLength: '800-1200 words' },
      carousel: { maxSlides: '300', format: 'PDF upload', bestSlides: '8-12' },
    },
    optimalHours: [7, 8, 9, 10, 12, 17],
    tips: [
      'Open with a hook line, then add a line break for "see more" trigger',
      'Personal stories with professional lessons get 5x engagement',
      'Document carousels (PDF) outperform image carousels',
      'Tuesday through Thursday mornings are LinkedIn gold hours',
    ],
  },
};

export const heatmapData = (() => {
  const data = [];
  const days = ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'];
  for (let d = 0; d < 7; d++) {
    for (let h = 0; h < 24; h++) {
      let count = 0;
      if (h >= 7 && h <= 21) {
        count = Math.floor(Math.random() * 5);
        if ((h >= 9 && h <= 11) || (h >= 17 && h <= 19)) count += 3;
        if (d < 5) count += 1;
      }
      data.push({ day: days[d], hour: h, count });
    }
  }
  return data;
})();

export const settingsData = {
  apis: [
    { name: 'OpenAI GPT-4', status: 'connected', lastChecked: '2 min ago' },
    { name: 'ElevenLabs', status: 'connected', lastChecked: '5 min ago' },
    { name: 'YouTube Data API', status: 'connected', lastChecked: '1 min ago' },
    { name: 'TikTok API', status: 'connected', lastChecked: '3 min ago' },
    { name: 'Instagram Graph API', status: 'warning', lastChecked: '15 min ago' },
    { name: 'Twitter/X API v2', status: 'connected', lastChecked: '2 min ago' },
    { name: 'LinkedIn API', status: 'error', lastChecked: '30 min ago' },
    { name: 'Reddit API', status: 'connected', lastChecked: '1 min ago' },
    { name: 'Google Trends', status: 'connected', lastChecked: '4 min ago' },
  ],
  scoringWeights: { velocity: 0.26, evergreen: 0.27, fit: 0.30, saturation: 0.17 },
  preferences: {
    niche: 'Software Engineering & DevOps',
    tone: 'Educational, slightly opinionated',
    postsPerDay: 4,
    voiceId: 'EXAVITQu4vr4xnSDxMaL',
  },
  notifications: {
    slackWebhook: 'https://hooks.slack.com/services/T0X.../B0X.../xxxx',
    emailAlerts: true,
    errorAlerts: true,
    dailyDigest: true,
  },
};

export const topPerformers = [
  { title: 'The Hidden Cost of Microservices', platform: 'TikTok', views: 128400, engagement: 12.5, sparkline: [20, 45, 80, 128, 125, 128, 127] },
  { title: 'I Cut My AWS Bill by 73%', platform: 'TikTok', views: 89700, engagement: 11.2, sparkline: [15, 30, 55, 78, 85, 89, 90] },
  { title: 'Senior Devs Moving to Monoliths', platform: 'YouTube', views: 45200, engagement: 8.7, sparkline: [5, 12, 25, 38, 42, 44, 45] },
  { title: 'Container Queries Thread', platform: 'Twitter/X', views: 34500, engagement: 8.1, sparkline: [8, 15, 22, 28, 32, 34, 35] },
  { title: 'Rust vs C++ Visual Guide', platform: 'Instagram', views: 23100, engagement: 17.0, sparkline: [3, 8, 14, 18, 21, 22, 23] },
];

export const upcomingSchedule = [
  { title: 'PostgreSQL vs MySQL: Which Should You Choose?', platform: 'YouTube', time: '3:00 PM', format: 'Short Video' },
  { title: 'Why Rust Dominates Embedded Systems', platform: 'TikTok', time: '5:30 PM', format: 'Short Video' },
  { title: 'Microservices Cost Analysis Carousel', platform: 'Instagram', time: '7:00 PM', format: 'Carousel' },
  { title: 'Vision Pro 2 Developer Guide', platform: 'YouTube', time: '9:00 PM', format: 'Short Video' },
  { title: 'RAG Pipeline Tips Thread', platform: 'Twitter/X', time: 'Tomorrow 8:00 AM', format: 'Thread' },
];
